FROM flink:1.17.1-scala_2.12-java8

# Install Python3 and create a symbolic link
RUN apt-get update && apt-get install -y \
    python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

RUN ls

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY ./fraud/ /fraud/
